version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicIdentity
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql             # ✅ Volume nommé pour persistance des données
      - ./identity-service/clinicIdentity.sql:/docker-entrypoint-initdb.d/clinicIdentity.sql
    networks:
      - clinic-network

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - clinic-network

  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    container_name: identity-service
    ports:
      - "9898:9898"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  mysql-data:    # ✅ Déclaration du volume nommé
