services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - clinic-network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctor-ms-db
    networks:
      - clinic-network

  doctor-ms:
    build:
      context: .
      dockerfile: doctor-ms/Dockerfile
    container_name: doctor-ms
    depends_on:
      - mysql
      - discovery-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge
