version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicIdentity
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./identity-service/clinicIdentity.sql:/docker-entrypoint-initdb.d/clinicIdentity.sql
    networks:
      - clinic-network

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - clinic-network

  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    container_name: identity-service
    ports:
      - "9898:9898"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

  doctor-ms:
    build:
      context: .
      dockerfile: doctor-ms/Dockerfile
    container_name: doctor-ms
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

  patient-ms:
    build:
      context: .
      dockerfile: patient-ms/Dockerfile
    container_name: patient-ms
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

  appointment-ms:
    build:
      context: .
      dockerfile: appointment-ms/Dockerfile
    container_name: appointment-ms
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

  medicalrecord-ms:
    build:
      context: .
      dockerfile: MedicalRecord-ms/Dockerfile
    container_name: medicalrecord-ms
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  mysql-data:
